version: "3.7"

services:
  prometheus:
    image: prom/prometheus:v2.12.0
    hostname: prometheus
    volumes:
      - "${PWD}/prometheus/conf.d/:/etc/prometheus/conf.d/"
      - "${PWD}/prometheus/rules/:/etc/prometheus/rules/"
      - "${PWD}/prometheus/file_sd/:/etc/prometheus/file_sd/"
      - "${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    links:
      - node_exporter
      - vmware_exporter
      - influxdb
    ports:
      - 9090:9090

  node_exporter:
    image: prom/node-exporter:latest
    hostname: node_exporter

  vmware_exporter:
    image: pryorda/vmware_exporter:v0.11.0
    entrypoint:
      - /usr/local/bin/vmware_exporter
      - -c
      - /opt/vmware_exporter/config.yml
    ports:
      - 9272:9272
    volumes:
      - "${PWD}/vmware_exporter/config.yml:/opt/vmware_exporter/config.yml"

  grafana:
    image: grafana/grafana:6.3.6
    hostname: grafana
    volumes:
      - grafana:/var/lib/grafana
      - "${PWD}/vmware_exporter/dashboards/cluster.json:/usr/share/grafana/public/dashboards/cluster.json"
      - "${PWD}/vmware_exporter/dashboards/esx.json:/usr/share/grafana/public/dashboards/esx.json"
      - "${PWD}/vmware_exporter/dashboards/esxi.json:/usr/share/grafana/public/dashboards/esxi.json"
      - "${PWD}/vmware_exporter/dashboards/virtualmachine.json:/usr/share/grafana/public/dashboards/virtualmachine.json"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    links:
      - prometheus
    ports:
      - 3000:3000

  influxdb:
    image: influxdb:1.7.8
    hostname: influxdb
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_DB=prometheus
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=supersecretpassword
      - INFLUXDB_USER=prom
      - INFLUXDB_USER_PASSWORD=secretpassword

volumes:
  influxdb:
  grafana: